"""Add Media and Tracking models

Revision ID: 03a06e2118cf
Revises: 277fa4bd54dc
Create Date: 2026-09-16 20:12:18.909178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03a06e2118cf'
down_revision: Union[str, Sequence[str], None] = '277fa4bd54dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('directors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('main_cast', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', name='uix_tmdb_type')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=False)
    op.create_table('user_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rewatch_count', sa.Integer(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uix_user_media')
    )
    op.create_index(op.f('ix_user_list_items_id'), 'user_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_list_items_media_id'), 'user_list_items', ['media_id'], unique=False)
    op.create_index(op.f('ix_user_list_items_user_id'), 'user_list_items', ['user_id'], unique=False)
    op.create_table('user_episode_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_list_item_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_list_item_id'], ['user_list_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_list_item_id', 'season_number', 'episode_number', name='uix_user_episode')
    )
    op.create_index(op.f('ix_user_episode_progress_id'), 'user_episode_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_episode_progress_user_list_item_id'), 'user_episode_progress', ['user_list_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_episode_progress_user_list_item_id'), table_name='user_episode_progress')
    op.drop_index(op.f('ix_user_episode_progress_id'), table_name='user_episode_progress')
    op.drop_table('user_episode_progress')
    op.drop_index(op.f('ix_user_list_items_user_id'), table_name='user_list_items')
    op.drop_index(op.f('ix_user_list_items_media_id'), table_name='user_list_items')
    op.drop_index(op.f('ix_user_list_items_id'), table_name='user_list_items')
    op.drop_table('user_list_items')
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
