"""add_backdrop_path_to_collection_items

Revision ID: 0b4d7c722660
Revises: 81058f0d6829
Create Date: 2026-09-22 12:56:45.367874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4d7c722660'
down_revision: Union[str, Sequence[str], None] = '81058f0d6829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('backdrop_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_items', 'backdrop_path')
    # ### end Alembic commands ###
