"""add_user_recommendations_table

Revision ID: 0dd68633e23b
Revises: 6e49b601f161
Create Date: 2026-09-27 18:55:37.344123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd68633e23b'
down_revision: Union[str, Sequence[str], None] = '6e49b601f161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('explore_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('upcoming_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personas_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_recommendations_user_id'), 'user_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommendations_user_id'), table_name='user_recommendations')
    op.drop_table('user_recommendations')
    # ### end Alembic commands ###
