"""add_genre_ids_to_media

Revision ID: 1eb6e368fbbb
Revises: a50cebb986d8
Create Date: 2026-09-21 21:57:19.801208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb6e368fbbb'
down_revision: Union[str, Sequence[str], None] = 'a50cebb986d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('genre_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'genre_ids')
    # ### end Alembic commands ###
