"""Add feature_vector to User

Revision ID: 3567ed86d453
Revises: 93ec529ff74c
Create Date: 2026-09-20 17:50:30.256111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3567ed86d453'
down_revision: Union[str, Sequence[str], None] = '93ec529ff74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feature_vector', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feature_vector')
    # ### end Alembic commands ###
