"""add_taste_clusters_to_users

Revision ID: 6e49b601f161
Revises: 0b4d7c722660
Create Date: 2026-09-22 14:18:21.832011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e49b601f161'
down_revision: Union[str, Sequence[str], None] = '0b4d7c722660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('taste_clusters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'taste_clusters')
    # ### end Alembic commands ###
