"""add_backdrop_path

Revision ID: 93ec529ff74c
Revises: 7454308ec835
Create Date: 2026-09-19 03:17:55.048872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ec529ff74c'
down_revision: Union[str, Sequence[str], None] = '7454308ec835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('backdrop_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'backdrop_path')
    # ### end Alembic commands ###
