"""add_cast_ids_crew_ids_to_media

Revision ID: a50cebb986d8
Revises: ad7e7c0b74ae
Create Date: 2026-09-21 21:46:24.324625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50cebb986d8'
down_revision: Union[str, Sequence[str], None] = 'ad7e7c0b74ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('cast_ids', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('crew_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'crew_ids')
    op.drop_column('media', 'cast_ids')
    # ### end Alembic commands ###
