"""add_embedding_to_media_and_users

Revision ID: a98017d96995
Revises: c391fd7138e9
Create Date: 2026-09-21 22:56:56.552409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98017d96995'
down_revision: Union[str, Sequence[str], None] = 'c391fd7138e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'embedding')
    op.drop_column('media', 'embedding')
    # ### end Alembic commands ###
