"""add_rating_to_user_episode_progress

Revision ID: ad7e7c0b74ae
Revises: b4970b7ab619
Create Date: 2026-09-21 16:53:08.907850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7e7c0b74ae'
down_revision: Union[str, Sequence[str], None] = 'b4970b7ab619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_episode_progress', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_episode_progress', 'rating')
    # ### end Alembic commands ###
