"""Add tracking and media tables

Revision ID: afe599a11cf0
Revises: 03a06e2118cf
Create Date: 2026-09-16 20:25:39.969178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe599a11cf0'
down_revision: Union[str, Sequence[str], None] = '03a06e2118cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'genres',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('media', 'directors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('media', 'main_cast',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('uix_tmdb_type'), 'media', type_='unique')
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.drop_constraint(op.f('uix_user_episode'), 'user_episode_progress', type_='unique')
    op.drop_constraint(op.f('uix_user_media'), 'user_list_items', type_='unique')
    op.create_index(op.f('ix_user_list_items_status'), 'user_list_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_list_items_status'), table_name='user_list_items')
    op.create_unique_constraint(op.f('uix_user_media'), 'user_list_items', ['user_id', 'media_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_user_episode'), 'user_episode_progress', ['user_list_item_id', 'season_number', 'episode_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_tmdb_id'), table_name='media')
    op.create_index(op.f('ix_media_tmdb_id'), 'media', ['tmdb_id'], unique=False)
    op.create_unique_constraint(op.f('uix_tmdb_type'), 'media', ['tmdb_id', 'media_type'], postgresql_nulls_not_distinct=False)
    op.alter_column('media', 'main_cast',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('media', 'directors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('media', 'genres',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
