"""Add runtime to media

Revision ID: b3e272f94bcb
Revises: ef7387c15c39
Create Date: 2026-09-18 22:48:53.188804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e272f94bcb'
down_revision: Union[str, Sequence[str], None] = 'ef7387c15c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('runtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'runtime')
    # ### end Alembic commands ###
