"""add_keywords_and_original_language_to_media

Revision ID: b4970b7ab619
Revises: 3567ed86d453
Create Date: 2026-09-21 15:30:19.071980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4970b7ab619'
down_revision: Union[str, Sequence[str], None] = '3567ed86d453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('original_language', sa.String(), nullable=True))
    op.add_column('media', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'keywords')
    op.drop_column('media', 'original_language')
    # ### end Alembic commands ###
