"""add_user_dismissed_recommendations_table

Revision ID: b9bd8a7b8889
Revises: 0dd68633e23b
Create Date: 2026-09-28 00:58:34.773866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9bd8a7b8889'
down_revision: Union[str, Sequence[str], None] = '0dd68633e23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dismissed_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', 'media_type', name='uq_user_dismissed_media')
    )
    op.create_index(op.f('ix_user_dismissed_recommendations_id'), 'user_dismissed_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_user_dismissed_recommendations_tmdb_id'), 'user_dismissed_recommendations', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_user_dismissed_recommendations_user_id'), 'user_dismissed_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dismissed_recommendations_user_id'), table_name='user_dismissed_recommendations')
    op.drop_index(op.f('ix_user_dismissed_recommendations_tmdb_id'), table_name='user_dismissed_recommendations')
    op.drop_index(op.f('ix_user_dismissed_recommendations_id'), table_name='user_dismissed_recommendations')
    op.drop_table('user_dismissed_recommendations')
    # ### end Alembic commands ###
