"""Add poster_path to media

Revision ID: ef7387c15c39
Revises: afe599a11cf0
Create Date: 2026-09-16 20:38:00.008562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7387c15c39'
down_revision: Union[str, Sequence[str], None] = 'afe599a11cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('poster_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'poster_path')
    # ### end Alembic commands ###
